version: "3"
services:
  server:
    image: word-of-wisdom-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
  client:
    image: word-of-wisdom-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
